language: java
jdk:
  - openjdk8

branches:
  only:
    - main

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r jong1-springboot-webservice *
  - mkdir -p deploy
  - mv jong1-springboot-webservice.zip deploy/jong1-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jong1-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jong1-springboot-build
    key: jong1-springboot-webservice.zip
    bundle_type: zip
    application: jong1-springboot-webservice
    deployment_group: jong1-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료시 매일로 알람
notifications:
  email:
    recipients:
      - whddnjs822@gmail.com